// src/components/GlobalNavigation.vue
<template>
  <nav>
    <a v-for="name in names" :key="name"
      :href='`${name}/`' 
      class="vue-global-nav-link"
    >
      {{name.replace(/^\w*?-/, "").toUpperCase()}}
    </a> 
  </nav>
</template>

<script>
export default {
  data() {
    return {
      names: []
    }
  },
  created() {
    this.generateList(require.context('@/', true, /index.html$/, 'lazy'))
  },
  methods: {
    generateList(r) {
      return r.keys().map(link => {
        let name = link.split("/")[1];
        console.log(name)
        if (name === "home") return;
        this.names.push(name);
      })
    }
  }
}
</script>

<style>
</style>

<style lang="scss" scoped>
</style>

// src/components/GlobalNavigation.jsx
import React from 'react';

function generateList(r) {
  return r.keys().map((link) => {
    let name = link.split("/")[1];
    console.log(name)
    if (name === "home") return;
    return (
      <a href={`${name}/`} 
        className="react-global-nav-link"
        key={name}
        >
        {name.replace(/^\w*?-/, "").toUpperCase()}
      </a>
    );
  });
};

const GlobalNavigation = () => {
  console.log("[GlobalNavigation] load...");
  return (
    <nav id='global-nav'>
      {generateList(require.context("@/", true, /index.html$/, "lazy"))}
    </nav>
  );
}

export default GlobalNavigation;
